extends: airbnb-base
globals:
  __DEV__: true
env:
  browser: true
  jest: true
rules:
  camelcase:
  - 0
  jsx-a11y/anchor-is-valid:
  - 0
  no-alert:
  - 0
  no-console:
  - 0
  no-trailing-spaces:
  - 0
  no-underscore-dangle:
  - 0
  object-curly-newline:
  - 0
  no-restricted-syntax:
  - 0
  no-await-in-loop:
  - 0
  no-loop-func:
  - 0
